### ISSUE TITLE
Adfly link for planet minecraft

### ISSUE THREAD

**Issue by me-rgb** [Flubberschnub/Flubberschnubs-Destiny-2-Guns#1]
ThAnK YoU SOOOOOOO much for the adfly virus! It REEAAAALy coool... jk I had to buy a new computer.

**Comment by Flubberschnub** [comment]
If you have a problem with adfly just use the direct link in the description on PMC.  Alternatively, you could just wait five seconds and hit "Skip Ad."

**Comment by me-rgb** [comment]
Yes but everyone else will get the virus.
